initial commit

diff --git a/.coder/img/coder/configure b/.coder/img/coder/configure
--- a/.coder/img/coder/configure
+++ b/.coder/img/coder/configure
@@ -1,4 +1,29 @@
 #!/bin/sh
 
-# The configure script runs when the workspace starts.
-# see https://coder.com/docs/coder/latest/images/configure
+#!/bin/bash
+
+# if nvm command fails, attempt to add it to our profile and PATH
+if ! command -v nvm &> /dev/null
+then
+    echo "nvm command not found... attempting to add to your profile via the install script"
+
+    # Create a .bash_profile file if it doesn't exist
+    if [ ! -f ~/.bash_profile ]; then
+        touch ~/.bash_profile
+        echo "#/bin/sh" > ~/.bash_profile
+        echo "source ~/.bashrc" >> ~/.bash_profile
+    fi
+
+    # Create a .bashrc if it doesn't exist
+    if [ ! -f ~/.bashrc ]; then
+        touch ~/.bashrc
+        echo "#/bin/sh" > ~/.bashrc
+    fi
+
+    # run the install script to add to profile
+    $NVM_DIR/install.sh
+
+    export NVM_DIR="/usr/bin/nvm"
+    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+fi
